# Generated by Django 5.0.1 on 2024-02-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalmodel_created_journalmodel_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalmodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
