# Generated by Django 5.0.1 on 2024-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalmodel_description_journalmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
