# Generated by Django 5.0.1 on 2024-02-18 14:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journalmodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalmodel',
            name='content_button',
        ),
        migrations.RemoveField(
            model_name='journalmodel',
            name='content_up',
        ),
        migrations.AddField(
            model_name='journalmodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1),
            preserve_default=False,
        ),
    ]
