# Generated by Django 5.0.1 on 2024-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_journalmodel_content_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalmodel',
            name='updated',
        ),
    ]
