# Generated by Django 5.0.1 on 2024-03-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_journalmodel_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalmodel',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journal'},
        ),
    ]
