# Generated by Django 5.0.3 on 2024-03-29 18:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journalmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
