# Generated by Django 5.0.3 on 2024-03-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_journalmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
