# Generated by Django 5.0.3 on 2024-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journalmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
