# Generated by Django 5.0.3 on 2024-04-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_tagmodel_addtagmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='slug',
        ),
    ]
