# Generated by Django 5.0.3 on 2024-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_journalmodel_canonical_journalmodel_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmodel',
            name='meta_description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalmodel',
            name='meta_title',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
