# Generated by Django 5.0.3 on 2024-06-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_journalmodel_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
