# Generated by Django 5.0.3 on 2024-06-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtagmodel',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.tagmodel'),
        ),
    ]
