# Generated by Django 5.0.3 on 2024-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_alter_journalmodel_options_alter_tagmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
