# Generated by Django 5.0.3 on 2024-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_alter_journalmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
