# Generated by Django 5.0.3 on 2024-06-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_alter_journalmodel_options_alter_tagmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
