# Generated by Django 5.0.3 on 2024-04-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AddQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='PersonalFeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.DeleteModel(
            name='AnswerRecommenderModel',
        ),
        migrations.AddField(
            model_name='addanswermodel',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.answermodel'),
        ),
        migrations.AddField(
            model_name='addquestionmodel',
            name='personal_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.personalfeaturemodel'),
        ),
        migrations.AddField(
            model_name='addanswermodel',
            name='personal_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.personalfeaturemodel'),
        ),
        migrations.AddField(
            model_name='addquestionmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel'),
        ),
    ]
