# Generated by Django 5.0.3 on 2024-04-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_addanswermodel_addquestionmodel_answermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalfeaturemodel',
            name='title',
        ),
    ]
