# Generated by Django 5.0.3 on 2024-04-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_remove_personalfeaturemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfeaturemodel',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel'),
            preserve_default=False,
        ),
    ]
