# Generated by Django 5.0.3 on 2024-04-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_personalfeaturemodel_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addanswermodel',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='addanswermodel',
            name='personal_feature',
        ),
        migrations.RemoveField(
            model_name='addquestionmodel',
            name='personal_feature',
        ),
        migrations.RemoveField(
            model_name='addquestionmodel',
            name='question',
        ),
        migrations.DeleteModel(
            name='AnswerModel',
        ),
        migrations.DeleteModel(
            name='AddAnswerModel',
        ),
        migrations.DeleteModel(
            name='AddQuestionModel',
        ),
    ]
