# Generated by Django 5.0.3 on 2024-04-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_answermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.answermodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel')),
            ],
        ),
    ]
