# Generated by Django 5.0.3 on 2024-04-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_addanswermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalFeatureModel',
            new_name='EducationalRecordModel',
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.questionmodel')),
            ],
        ),
    ]
