# Generated by Django 5.0.3 on 2024-04-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_rename_personalfeaturemodel_educationalrecordmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addanswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_rel', to='recommender.questionmodel'),
        ),
    ]
