# Generated by Django 5.0.3 on 2024-04-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='NewsletterSubscriptionModel',
        ),
    ]
