# Generated by Django 5.0.1 on 2024-03-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastmodel',
            options={'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcast'},
        ),
    ]
