# Generated by Django 5.0.1 on 2024-03-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcastmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastmodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
