# Generated by Django 5.0.1 on 2024-02-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_visa', models.IntegerField()),
                ('fix_rejection', models.IntegerField()),
                ('founder_image', models.ImageField(upload_to='images/home/')),
                ('founder_video', models.FileField(upload_to='videos/home/')),
                ('content_bottom', models.TextField(max_length=10000)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/feedback/')),
                ('city', models.CharField(max_length=64)),
                ('rank', models.IntegerField()),
                ('content', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(upload_to='images/partner_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.ImageField(upload_to='images/social_media/')),
                ('address', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FixRejectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_fix_reject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessVisaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_success', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
