# Generated by Django 5.0.1 on 2024-02-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reservemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
