# Generated by Django 5.0.1 on 2024-02-08 07:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reservemodel_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehomemodel',
            name='content_bottom',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
