# Generated by Django 5.0.1 on 2024-02-16 06:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_basehomemodel_content_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehomemodel',
            name='user_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basehomemodel',
            name='content_bottom',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
