# Generated by Django 5.0.1 on 2024-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_benefitmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitmodel',
            name='row',
            field=models.TextField(),
        ),
    ]
