# Generated by Django 5.0.1 on 2024-02-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_benefitmodel_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehomemodel',
            name='content_up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_home', to='home.benefitmodel'),
            preserve_default=False,
        ),
    ]
