# Generated by Django 5.0.1 on 2024-02-16 20:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_basehomemodel_content_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about/person/')),
                ('full_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('video', models.FileField(upload_to='videos/about/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_about', to='home.aboutpersonmodel')),
            ],
        ),
    ]
