# Generated by Django 5.0.1 on 2024-02-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutpersonmodel_aboutmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='person',
        ),
    ]
