# Generated by Django 5.0.1 on 2024-02-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_benefitmodel_base_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitmodel',
            name='base_home',
        ),
    ]
