# Generated by Django 5.0.1 on 2024-02-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_benefitmodel_base_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitmodel',
            name='base_home',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.basehomemodel'),
            preserve_default=False,
        ),
    ]
