# Generated by Django 5.0.1 on 2024-03-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_benefitmodel_base_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='aboutpersonmodel',
            options={'verbose_name': 'About Person', 'verbose_name_plural': 'About Person'},
        ),
        migrations.AlterModelOptions(
            name='basehomemodel',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='partnerlogomodel',
            options={'verbose_name': 'Partner Logo', 'verbose_name_plural': 'Partner Logo'},
        ),
        migrations.AlterModelOptions(
            name='reservemodel',
            options={'verbose_name': 'Reserve', 'verbose_name_plural': 'Reserves'},
        ),
        migrations.AlterModelOptions(
            name='socialmediamodel',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='rank',
            new_name='rate',
        ),
    ]
