# Generated by Django 5.0.1 on 2024-03-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_aboutmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefitmodel',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefit'},
        ),
    ]
