# Generated by Django 5.0.3 on 2024-03-29 18:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_benefitmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basehomemodel',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='basehomemodel',
            name='content_bottom',
            field=tinymce.models.HTMLField(),
        ),
    ]
