# Generated by Django 5.0.3 on 2024-04-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_bannermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
    ]
