# Generated by Django 5.0.1 on 2024-02-16 07:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_up', django_ckeditor_5.fields.CKEditor5Field()),
                ('content_bottom', django_ckeditor_5.fields.CKEditor5Field()),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_program', to='programs.programlistmodel')),
            ],
        ),
    ]
