# Generated by Django 5.0.1 on 2024-02-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_programmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodel',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='programmodel',
            name='icon',
            field=models.ImageField(default=1, upload_to='images/programs/icon/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgramListModel',
        ),
    ]
