# Generated by Django 5.0.1 on 2024-02-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_rename_content_bottom_programmodel_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramDescription',
            new_name='ProgramDescriptionModel',
        ),
    ]
