# Generated by Django 5.0.1 on 2024-02-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_rename_programdescription_programdescriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programdescriptionmodel',
            name='program',
        ),
        migrations.AddField(
            model_name='programmodel',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_descr', to='programs.programdescriptionmodel'),
            preserve_default=False,
        ),
    ]
