# Generated by Django 5.0.1 on 2024-02-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_remove_programdescriptionmodel_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodel',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_descr', to='programs.programdescriptionmodel'),
        ),
    ]
