# Generated by Django 5.0.3 on 2024-03-29 18:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_programdescriptionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
