# Generated by Django 5.0.3 on 2024-04-28 11:17

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_alter_programmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('icon', models.ImageField(upload_to='images/programs/category/icon/')),
                ('title', models.CharField(max_length=256)),
                ('first_description', tinymce.models.HTMLField()),
                ('second_description', tinymce.models.HTMLField()),
                ('video', models.FileField(upload_to='videos/programs/category/')),
                ('third_description', tinymce.models.HTMLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='programmodel',
            name='description',
        ),
        migrations.CreateModel(
            name='SubCategoryProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=32)),
                ('title', tinymce.models.HTMLField()),
                ('first_description', tinymce.models.HTMLField()),
                ('second_description', tinymce.models.HTMLField()),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.categoryprogrammodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgramDescriptionModel',
        ),
        migrations.DeleteModel(
            name='ProgramModel',
        ),
    ]
