# Generated by Django 5.0.3 on 2024-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_categoryprogrammodel_remove_programmodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryprogrammodel',
            old_name='first_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subcategoryprogrammodel',
            old_name='first_description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='subcategoryprogrammodel',
            old_name='second_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='categoryprogrammodel',
            name='second_description',
        ),
        migrations.AddField(
            model_name='categoryprogrammodel',
            name='banner',
            field=models.ImageField(default=111, upload_to='images/programs/category/banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='banner',
            field=models.ImageField(default=111111, upload_to='images/programs/subcategory/banner/'),
            preserve_default=False,
        ),
    ]
