# Generated by Django 5.0.3 on 2024-05-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_rename_first_description_categoryprogrammodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryprogrammodel',
            name='third_description',
        ),
    ]
