# Generated by Django 5.0.3 on 2024-05-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_remove_categoryprogrammodel_third_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryprogrammodel',
            name='video',
        ),
    ]
