# Generated by Django 5.0.3 on 2024-06-01 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_remove_categoryprogrammodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprogrammodel',
            name='canonical',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryprogrammodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryprogrammodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryprogrammodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryprogrammodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='canonical',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
