# Generated by Django 5.0.3 on 2024-06-05 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_categoryprogrammodel_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category Tag',
                'verbose_name_plural': 'categories Tag',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Subcategory Tag',
                'verbose_name_plural': 'Subcategories Tag',
            },
        ),
        migrations.CreateModel(
            name='AddCategoryTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tag', to='programs.categoryprogrammodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.categorytagmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddSubcategoryTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_tag', to='programs.categoryprogrammodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.subcategorytagmodel')),
            ],
        ),
    ]
