# Generated by Django 5.0.3 on 2024-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_categorytagmodel_subcategorytagmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryprogrammodel',
            name='description',
        ),
        migrations.AddField(
            model_name='subcategoryprogrammodel',
            name='media',
            field=models.FileField(default=1, upload_to='media/programs/subcategory/'),
            preserve_default=False,
        ),
    ]
