# Generated by Django 5.0.3 on 2024-06-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategorytagmodel',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.categorytagmodel'),
        ),
        migrations.AlterField(
            model_name='addsubcategorytagmodel',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.subcategorytagmodel'),
        ),
    ]
