# Generated by Django 5.0.3 on 2024-06-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_alter_addcategorytagmodel_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprogrammodel',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='subcategoryprogrammodel',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
